---
- name: apt packages
  apt: pkg={{item}}
  with_items:
  - nginx
- name: deploy content
  git: repo=https://github.com/mlin/mlin.net.git dest=/home/mlin/www depth=1 
- file: path=/home/mlin/www state=directory owner=mlin group=www-data mode=0644
- copy: src=sites-enabled.mlin.net dest=/etc/nginx/sites-enabled/mlin.net mode=0644 owner=root group=root
- file: path=/etc/nginx/sites-enabled/default state=absent
- service: name=nginx enabled=yes state=reloaded
